language: python

dist: xenial
python:
  - "3.6"

services:
  - mysql
  - docker

env:
  - DJANGO_VERSION=2.1

before_install:
  - sudo apt-get install -y libffi-dev gcc python-dev musl-dev

install:
  - pip install -r requirements.txt

before_script:
  - mkdir -p ../config/auth/
  # Create the settings_* files
  - cp calipsoplus/settings_calipso.py.example calipsoplus/settings_calipso.py
  - cp calipsoplus/settings_unittests.py.example calipsoplus/settings_unittests.py

script:
  - python manage.py test --settings=calipsoplus.settings_unittests